### ISSUE TITLE
REPORTE DE BIZAGI ICP

### ISSUE THREAD

**Issue by YaelStO** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-jdgras#1]
[
[PRACTICA 2 BIZAGI ICP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-jdgras/files/12825880/PRACTICA.2.BIZAGI.ICP.pdf)
](url)

**Comment by 27Fer12** [comment]
Portada : 25
Procedimiento : 22
Figuras, ilustraciones y fotografías. : 20
Resultados y conclusiones : 22
calificación : 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
